language: python
python:
- '2.7'
- '3.4'
- '3.5'
- '3.6'
install:
- pip install pylint
script: python string_spaces_checkers.py
deploy:
  provider: pypi
  distributions: sdist bdist_wheel
  user: bohanzhang
  password:
    secure: YuCPQkV31I0hX5qTizABwq7Tjr+z8qShToeo0drIP8qe09purXxg4z/bobHXKE9IhY63A2T/q7HGiOh1bZ8tzvYK0P90bFW8SymrRjZ7la5fXM0p/5ukEUaDWd6Kb9kZTLe7VuXrRlKR2CAB94L6nBXs38K11CCHSaAvBPGFHOtnA3nnx2i4sZ1KLSMwsSEDBdm4SFQhgJVYNkB0kxTCYO8vTNuXhfn4vUpH8p5h2HBZddL4MB0q4oGMbXrPSTdhHIZqNO7l0CnKZtrkvNO0pFZf0/4N+mYQPyY4b1OIwr7SDetnyPquAQjf2+kQI3jPP0LcSmt2HJ6/q2V9HOg7O9BKk/l4/Ud8rPvrzYeB1fzyT5WfEotbXiylGhv4n9hT9Vfv4B3aNhVXHKK4VV3vGCr4VnyanqCDmGzD/hh3CuAOQtVdeVsZWpc6gzu0JS+TDwIufhmdJlOKeOwuFge72cniko5Lg3cnTmuRcztvfQSymEpbqceraCroyCVL/ZENP4aGn5FQCEDqGE+iHqqOZyw5A7GysZk8SyeGDC9F6CVWCV9o2TkTK2lqYrLD888isdMRwfXag+SN4RMGR2FLlFeftgcYaeZ74HDTF2QN/07IYw4N2S5lZEkNZkUF2Xxy0XRUO74kFoKpXwgZnYFy2cSZbb1QojB3vkkch5hRtdM=
  on:
    tags: true
