language: python
python:
- '2.7'
- '3.4'
- '3.5'
- '3.6'
install:
- pip install pylint
script: python string_spaces_checkers.py
deploy:
  provider: pypi
  distributions: sdist bdist_wheel
  user: bohanzhang
  password:
    secure: a0nkuTAL0NzjRwlkkS4GzTs2MLOey1WgoEv5CgqWdVm4u+LA3MBYBOz5vlDW/gAsM8P5hRZzso4+HGEbU4sFEOkwE4WhwAfxVUUjDy+mhjfXf9XJ8gjzL1NF37KQvGLVW5HRZtGWZzM3h3vTe0TXlDqwLf1BGyi8x/9WZl0eRnd9n2s0fgtnWyFWMd6AkodPFKfC+lEUkK8OtMWPCMdJS3VjbCqx0xsmEYu2KM16iDIb5w5qusA7Cbww5BflquN0OOBLNBTIAfmYWhnUqzD+wMkI8jWDf7BDppNU6NzYaXfrfmoLmXcwA/dZ3B92Ty2SVESE1XJiRsgE1fZxoxnAX99npg/ajQksdEU2HKcXt3xFQfDJsFWISgO4sxwESPhwk8vcQp55Ibtg1KxwdZRDgfpsDpZDWamk+YSJTxE5bTxVttv2ntjZqzYIFMTY4r/6J3etmj2icIDvq52ivWE4VjhnprK51rj2qb8NHL/tmp3Ax2HeCPYMm0w9pE4KnDarJvTkiOk0Qe9pTf1QuxN7TAwyv8ZjuWQ5A3rGtbgc8Mzi1Vh7ADV0pYtaVlvupq97ia7R4zIhRJdiKsCjGJhsGMgVaiZl42sVV7fKZCpDLfW+rLbCFRqAxfTzFlPmb6yuO43qse8+582YrQO9X9Ss3sCc+PqvM7RQUViDeNto6+Q=
  on:
    tags: true
